# Generated by Django 2.0.2 on 2018-03-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapWebPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='name',
            field=models.CharField(default='empty', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='horse',
            name='total_placed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='horse',
            name='total_prize',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='horse',
            name='total_wins',
            field=models.IntegerField(default=0),
        ),
    ]
