# Generated by Django 2.0.2 on 2018-03-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapWebPage', '0003_auto_20180319_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='group',
            field=models.CharField(default='~UNKNOWN', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='race_class',
            field=models.CharField(default='~UNKNOWN', max_length=10, null=True),
        ),
    ]
