# Generated by Django 2.0.2 on 2018-03-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapWebPage', '0004_auto_20180319_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horseracelink',
            name='comment',
            field=models.CharField(default='~UNKNOWN', max_length=255),
        ),
        migrations.AlterField(
            model_name='horseracelink',
            name='draw',
            field=models.IntegerField(null=True),
        ),
    ]
