# Generated by Django 2.0.2 on 2018-03-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapWebPage', '0005_auto_20180319_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horseracelink',
            name='position',
            field=models.CharField(default='~UNKNOWN', max_length=10),
        ),
    ]
