# Generated by Django 2.0.2 on 2018-03-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapWebPage', '0006_auto_20180319_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horseracelink',
            name='comment',
            field=models.CharField(default='~UNKNOWN', max_length=255, null=True),
        ),
    ]
